num=(1,3,2,4,6,5)
print("The Original tuple num is : ", num) 
num2= sorted(num) 
print("The Original tuple num2 is : ", num2) 
num3= sorted(num2, reverse= True)
print("The sorted list num3 is descending order using sorted is: " , num3)
num4 = tuple(num2) 
print("The sorted tuple num4 is : " ,num4)
print("The original tuple num is: ",num)
